spring.application.name=bff-service
server.port=8080

url.ms.recursos=http://localhost:8081/api/rrhh/empleados
url.ms.proyectos=http://localhost:8082/api/proyectos
url.ms.notifications=http://localhost:8083/api/notificaciones